title: "{foo:bar}"
email: amandeepspdhr@gmail.com
description: > 
  Blog about my ramblings in Machine Learning and Software
  Engineering. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amandeepsp.github.io"
github_username: amandeepsp

# Build settings
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
show_excerpts: true
google_analytics: UA-112449883-1
disqus:
  shortname: amandeeps-blog