import "prismjs/themes/prism-solarizedlight.css"
import "prismjs/plugins/line-numbers/prism-line-numbers.css"
import "katex/dist/katex.min.css"
import "./src/styles/syntax-highlight.css"
import "./src/styles/global.css"
import "typeface-montserrat"
import "typeface-rubik"
import "typeface-karla"
